#spring.jpa.hibernate.ddl-auto: update
#spring.datasource.url: jdbc:mysql://localhost:3306/dbb
#spring.datasource.username: root
#spring.datasource.password: root
#spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql: true
spring.main.allow-bean-definition-overriding: true 

#primary db 
spring.datasource.primary.url: jdbc:mysql://localhost:3306/primary
spring.datasource.primary.username: root
spring.datasource.primary.password: root
spring.datasource.primary.driverClassName: com.mysql.cj.jdbc.Driver 
spring.datasource.primary.dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
spring.datasource.primary.ddl_auto: create-drop
#
##secondary db 
spring.datasource.secondary.url: jdbc:mysql://localhost:3306/secondary
spring.datasource.secondary.username: root
spring.datasource.secondary.password: root
spring.datasource.secondary.driverClassName: com.mysql.cj.jdbc.Driver 
spring.datasource.secondary.dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
spring.datasource.secondary.ddl_auto: create-drop


